pet-project/electro_car/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name="blogs", ),
    path('<int:blog_id>', views.detail, name="detail"),
]

pet-project/electro_car/electro_car/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from electric_car_dir import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('profile', views.profile, name='profile'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet-project/electro_car/blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

pet-project/electro_car/electric_car_dir/models.py
from django.db import models


class ElectricCarDir(models.Model):
    car_name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='electric_car_dir/images/')
    url = models.URLField(blank=True)

pet-project/electro_car/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/blogs.html', {"blogs": blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/details.html', {'blog': blog})

# Create your views here.

pet-project/electro_car/electric_car_dir/views.py
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.shortcuts import render, redirect
from .models import ElectricCarDir
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate


def index(request):
    projects = ElectricCarDir.objects.all()
    return render(request, 'electric_car_dir/index.html', {'projects': projects})


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')


def profile(request):
    return render(request, 'electric_car_dir/profile.html')


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'electric_car_dir/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'electric_car_dir/loginuser.html', {'form': AuthenticationForm(), 'error': "Неверные данные для входа"})
        else:
            login(request, user)
            return redirect('profile')


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'electric_car_dir/signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('profile')
            except IntegrityError:
                return render(request, 'electric_car_dir/signupuser.html',
                              {'form': UserCreationForm(), 'error': 'Такой логин уже существует'})
        else:
            return render(request, 'electric_car_dir/signupuser.html',
                          {'form': UserCreationForm(), 'error': 'Пароли не совпадают'})

pet-project/electro_car/blog/templates/blog/blogs.html
{% extends 'electric_car_dir/base.html' %}
{% block content %}

<h1>Blog</h1>
<h2 class="count">Постов: {{ blogs.count }}</h2>
{% for blog in blogs %}
<div class="element">
    <h2 class="top"><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a></h2>
    <div class="blog_text">
        <h5>{{ blog.date|date:'j E Y' }}</h5>
        <p>{{ blog.description|truncatechars:360 }}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

pet-project/electro_car/blog/templates/blog/details.html
{% extends 'electric_car_dir/base.html' %}
{% block content %}
<div class="detail">
    <h1>{{ blog.title }}</h1>
    <h2>-- {{ blog.date|date:'j E Y' }} --</h2>
    {{ blog.description|safe }}


</div>


{% endblock %}

pet-project/electro_car/electric_car_dir/templates/electric_car_dir/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% if user.is_authenticated %}
<div class="menu_user">
    <div class="wrap">
        <ul>
            <li class="log">Пользователь: {{ user.username }}</li>
            <li>
                <form action="{% url 'logoutuser' %}" method="post">
                    {% csrf_token %}
                    <button class="top">Выход</button>
                </form></li>

        </ul>
   </div>
</div>
{% else %}
<div class="menu_user">
    <div class="wrap">
        <ul>
            <li><a href="{% url 'signupuser' %}">Регистрация</a></li>
            <li><a href="{% url 'loginuser' %}">Вход</a></li>
        </ul>
    </div>
</div>
{% endif %}
<div class="menu">
    <div class="wrap">
        <div class="logo">
            <a href="{% url 'index' %}"><img src="{% static 'skills/logo.png' %}" alt=""></a>
        </div>
        <ul>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'blog:blogs' %}">Блог</a></li>
        </ul>
    </div>
</div>
  <div class="content">
      <div class="wrap">
          {% block content %}
          {% endblock %}
      </div>
  </div>
</body>
</html>

pet-project/electro_car/electric_car_dir/templates/electric_car_dir/index.html
{% extends 'electric_car_dir/base.html' %}
{% block content %}
{% load static %}
<h1>Электрический транспорт</h1>
<div class="img">
    <img src="{% static 'electric_car_dir/leaf_baikal.jpg' %}" alt="">
</div>
<h2>Массовые электромобили, доступные в Сибири:</h2>
<div class="block">
    {% for project in projects %}
    <div class="element">
        <div><img src="{{ project.image.url }}" alt=""></div>
        <div class="text">
            <h2><a href="{{ project.url }}" target="_blank">{{ project.car_name }}</a></h2>
            <p>{{ project.description }}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

pet-project/electro_car/electric_car_dir/templates/electric_car_dir/loginuser.html
{% extends 'electric_car_dir/base.html' %}
{% block content %}


    <h1>Авторизация</h1>
    <h2>{{ error }}</h2>
    <form method="post" class="bg">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="center"><button class="btn">Авторизация</button> </div>
    </form>

{% endblock %}

pet-project/electro_car/electric_car_dir/templates/electric_car_dir/profile.html
{% extends 'electric_car_dir/base.html' %}
{% block content %}
<h1>Профиль пользователя: {{ user.username }}</h1>



{% endblock %}

pet-project/electro_car/electric_car_dir/templates/electric_car_dir/signupuser.html
{% extends 'electric_car_dir/base.html' %}
{% block content %}
<h1>Регистрация</h1>
<form method="post" class="register">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn">Зарегистрироваться</button>

</form>



{% endblock %}